### PR TITLE
Add collapse component for credentials

### LINKED ISSUE #18: [UI] Change VP view to an accordeon
Example:

image

### PR DESCRIPTION
**Pull request by simne7**
Closes #18 

Uses a accordion to display the list of credentials. 

## Screenshot:

Screenshot from 2024-02-07 12-55-07

## Todos

- [ ] what goes into the item title?

## Test

To test run `just run-preview` and modify `src/lib/identinet/fixtures/storageItems.js` (e.g. by duplicating the `verifiableCredential` item or adding multiple `credentialSubject` claims.)

```js
export const idPlusItem = {
  "did:web:id-plus-example.identinet.io": {
    presentation: {
      // "@context": ...,
      type: ["VerifiablePresentation"],
      verifiableCredential: [
        {
          // "@context": ...
          type: ["VerifiableCredential"],
          credentialSubject: {
            id: "did:web:id-plus-example.identinet.io",
            id2: "did:web:id-plus-example.identinet.io",
            id3: "did:web:id-plus-example.identinet.io",
          },
          issuer: "did:web:id-plus-example.identinet.io",
          // ....
        },
        {
          // "@context": ...,
          type: ["VerifiableCredential"],
          credentialSubject: {
            id: "did:web:id-plus-example.identinet.io",
            id2: "did:web:id-plus-example.identinet.io",
          },
          issuer: "did:web:id-plus-example.identinet.io2",
          // ...
```

### CODE REVIEW

**Comment by simne7** [comment]
image

**Comment by simne7** [comment]
image

**Review by jceb — APPROVED** [review]
Looks great! I'm wondering about the use of `className` vs. `class` attributes. Do you have a preference?

**Comment by simne7** [comment]
Not really. Let's use `class`. The shorter, the better :)

**Pull request merged**
